INSERT INTO carta
(nombre, ps, tipo, habilidad, descripcion_habilidad, coste_energia, retirada, ataque, dano_ataque, descripcion_ataque, debilidad, resistencia, rareza)
VALUES
    ('Bulbasaur', 70, 'Planta', 'Clorofila', 'Aumenta su poder natural', 1, 1, 'Latigo Cepa', 40, 'Ataque de tipo planta', 'Fuego', 10, 'Comun'),
    ('Ivysaur', 70, 'Planta', 'Clorofila', 'Aumenta su poder natural', 1, 1, 'Latigo Cepa', 40, 'Ataque de tipo planta', 'Fuego', 10, 'Comun'),
    ('Venusaur', 120, 'Planta', 'Clorofila', 'Aumenta su poder natural', 2, 2, 'Latigo Cepa', 80, 'Ataque de tipo planta', 'Fuego', 20, 'Rara'),
    ('Charmander', 70, 'Fuego', 'Mar de Llamas', 'Aumenta el daño de fuego', 1, 1, 'Lanzallamas', 40, 'Ataque de tipo fuego', 'Agua', 10, 'Comun'),
    ('Charmeleon', 70, 'Fuego', 'Mar de Llamas', 'Aumenta el daño de fuego', 1, 1, 'Lanzallamas', 40, 'Ataque de tipo fuego', 'Agua', 10, 'Comun'),
    ('Charizard', 120, 'Fuego', 'Mar de Llamas', 'Aumenta el daño de fuego', 2, 2, 'Lanzallamas', 80, 'Ataque de tipo fuego', 'Agua', 20, 'Rara'),
    ('Squirtle', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Wartortle', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Blastoise', 120, 'Agua', 'Torrente', 'Aumenta el poder de agua', 2, 2, 'Pistola Agua', 80, 'Ataque de tipo agua', 'Electrico', 20, 'Rara'),
    ('Caterpie', 70, 'Bicho', 'Enjambre', 'Aumenta ataques de bicho', 1, 1, 'Picadura', 40, 'Ataque de tipo bicho', 'Fuego', 10, 'Comun'),
    ('Metapod', 70, 'Bicho', 'Enjambre', 'Aumenta ataques de bicho', 1, 1, 'Picadura', 40, 'Ataque de tipo bicho', 'Fuego', 10, 'Comun'),
    ('Butterfree', 70, 'Bicho', 'Enjambre', 'Aumenta ataques de bicho', 1, 1, 'Picadura', 40, 'Ataque de tipo bicho', 'Fuego', 10, 'Comun'),
    ('Weedle', 70, 'Bicho', 'Enjambre', 'Aumenta ataques de bicho', 1, 1, 'Picadura', 40, 'Ataque de tipo bicho', 'Fuego', 10, 'Comun'),
    ('Kakuna', 70, 'Bicho', 'Enjambre', 'Aumenta ataques de bicho', 1, 1, 'Picadura', 40, 'Ataque de tipo bicho', 'Fuego', 10, 'Comun'),
    ('Beedrill', 70, 'Bicho', 'Enjambre', 'Aumenta ataques de bicho', 1, 1, 'Picadura', 40, 'Ataque de tipo bicho', 'Fuego', 10, 'Comun'),
    ('Pidgey', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Pidgeotto', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Pidgeot', 120, 'Normal', 'Adaptable', 'Mejora ataques normales', 2, 2, 'Placaje', 80, 'Ataque de tipo normal', 'Lucha', 20, 'Rara'),
    ('Rattata', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Raticate', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Spearow', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Fearow', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Ekans', 70, 'Veneno', 'Punto Toxico', 'Puede envenenar al rival', 1, 1, 'Acido', 40, 'Ataque de tipo veneno', 'Psiquico', 10, 'Comun'),
    ('Arbok', 70, 'Veneno', 'Punto Toxico', 'Puede envenenar al rival', 1, 1, 'Acido', 40, 'Ataque de tipo veneno', 'Psiquico', 10, 'Comun'),
    ('Pikachu', 70, 'Electrico', 'Electricidad Estatica', 'Puede paralizar al rival', 1, 1, 'Impactrueno', 40, 'Ataque de tipo electrico', 'Tierra', 10, 'Comun'),
    ('Raichu', 120, 'Electrico', 'Electricidad Estatica', 'Puede paralizar al rival', 2, 2, 'Impactrueno', 80, 'Ataque de tipo electrico', 'Tierra', 20, 'Rara'),
    ('Sandshrew', 70, 'Tierra', 'Velo Arena', 'Mejora evasion en arena', 1, 1, 'Terremoto', 40, 'Ataque de tipo tierra', 'Agua', 10, 'Comun'),
    ('Sandslash', 70, 'Tierra', 'Velo Arena', 'Mejora evasion en arena', 1, 1, 'Terremoto', 40, 'Ataque de tipo tierra', 'Agua', 10, 'Comun'),
    ('Nidoran Hembra', 70, 'Veneno', 'Punto Toxico', 'Puede envenenar al rival', 1, 1, 'Acido', 40, 'Ataque de tipo veneno', 'Psiquico', 10, 'Comun'),
    ('Nidorina', 70, 'Veneno', 'Punto Toxico', 'Puede envenenar al rival', 1, 1, 'Acido', 40, 'Ataque de tipo veneno', 'Psiquico', 10, 'Comun'),
    ('Nidoqueen', 120, 'Veneno', 'Punto Toxico', 'Puede envenenar al rival', 2, 2, 'Acido', 80, 'Ataque de tipo veneno', 'Psiquico', 20, 'Rara'),
    ('Nidoran Macho', 70, 'Veneno', 'Punto Toxico', 'Puede envenenar al rival', 1, 1, 'Acido', 40, 'Ataque de tipo veneno', 'Psiquico', 10, 'Comun'),
    ('Nidorino', 70, 'Veneno', 'Punto Toxico', 'Puede envenenar al rival', 1, 1, 'Acido', 40, 'Ataque de tipo veneno', 'Psiquico', 10, 'Comun'),
    ('Nidoking', 120, 'Veneno', 'Punto Toxico', 'Puede envenenar al rival', 2, 2, 'Acido', 80, 'Ataque de tipo veneno', 'Psiquico', 20, 'Rara'),
    ('Clefairy', 70, 'Hada', 'Gran Encanto', 'Puede reducir ataque rival', 1, 1, 'Brillo Magico', 40, 'Ataque de tipo hada', 'Veneno', 10, 'Comun'),
    ('Clefable', 70, 'Hada', 'Gran Encanto', 'Puede reducir ataque rival', 1, 1, 'Brillo Magico', 40, 'Ataque de tipo hada', 'Veneno', 10, 'Comun'),
    ('Vulpix', 70, 'Fuego', 'Mar de Llamas', 'Aumenta el daño de fuego', 1, 1, 'Lanzallamas', 40, 'Ataque de tipo fuego', 'Agua', 10, 'Comun'),
    ('Ninetales', 120, 'Fuego', 'Mar de Llamas', 'Aumenta el daño de fuego', 2, 2, 'Lanzallamas', 80, 'Ataque de tipo fuego', 'Agua', 20, 'Rara'),
    ('Jigglypuff', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Wigglytuff', 120, 'Normal', 'Adaptable', 'Mejora ataques normales', 2, 2, 'Placaje', 80, 'Ataque de tipo normal', 'Lucha', 20, 'Rara'),
    ('Zubat', 70, 'Veneno', 'Punto Toxico', 'Puede envenenar al rival', 1, 1, 'Acido', 40, 'Ataque de tipo veneno', 'Psiquico', 10, 'Comun'),
    ('Golbat', 70, 'Veneno', 'Punto Toxico', 'Puede envenenar al rival', 1, 1, 'Acido', 40, 'Ataque de tipo veneno', 'Psiquico', 10, 'Comun'),
    ('Oddish', 70, 'Planta', 'Clorofila', 'Aumenta su poder natural', 1, 1, 'Latigo Cepa', 40, 'Ataque de tipo planta', 'Fuego', 10, 'Comun'),
    ('Gloom', 70, 'Planta', 'Clorofila', 'Aumenta su poder natural', 1, 1, 'Latigo Cepa', 40, 'Ataque de tipo planta', 'Fuego', 10, 'Comun'),
    ('Vileplume', 120, 'Planta', 'Clorofila', 'Aumenta su poder natural', 2, 2, 'Latigo Cepa', 80, 'Ataque de tipo planta', 'Fuego', 20, 'Rara'),
    ('Paras', 70, 'Bicho', 'Enjambre', 'Aumenta ataques de bicho', 1, 1, 'Picadura', 40, 'Ataque de tipo bicho', 'Fuego', 10, 'Comun'),
    ('Parasect', 70, 'Bicho', 'Enjambre', 'Aumenta ataques de bicho', 1, 1, 'Picadura', 40, 'Ataque de tipo bicho', 'Fuego', 10, 'Comun'),
    ('Venonat', 70, 'Bicho', 'Enjambre', 'Aumenta ataques de bicho', 1, 1, 'Picadura', 40, 'Ataque de tipo bicho', 'Fuego', 10, 'Comun'),
    ('Venomoth', 70, 'Bicho', 'Enjambre', 'Aumenta ataques de bicho', 1, 1, 'Picadura', 40, 'Ataque de tipo bicho', 'Fuego', 10, 'Comun'),
    ('Diglett', 70, 'Tierra', 'Velo Arena', 'Mejora evasion en arena', 1, 1, 'Terremoto', 40, 'Ataque de tipo tierra', 'Agua', 10, 'Comun'),
    ('Dugtrio', 70, 'Tierra', 'Velo Arena', 'Mejora evasion en arena', 1, 1, 'Terremoto', 40, 'Ataque de tipo tierra', 'Agua', 10, 'Comun'),
    ('Meowth', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Persian', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Psyduck', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Golduck', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Mankey', 70, 'Lucha', 'Foco Interno', 'Evita retroceder', 1, 1, 'Golpe Karate', 40, 'Ataque de tipo lucha', 'Psiquico', 10, 'Comun'),
    ('Primeape', 70, 'Lucha', 'Foco Interno', 'Evita retroceder', 1, 1, 'Golpe Karate', 40, 'Ataque de tipo lucha', 'Psiquico', 10, 'Comun'),
    ('Growlithe', 70, 'Fuego', 'Mar de Llamas', 'Aumenta el daño de fuego', 1, 1, 'Lanzallamas', 40, 'Ataque de tipo fuego', 'Agua', 10, 'Comun'),
    ('Arcanine', 120, 'Fuego', 'Mar de Llamas', 'Aumenta el daño de fuego', 2, 2, 'Lanzallamas', 80, 'Ataque de tipo fuego', 'Agua', 20, 'Rara'),
    ('Poliwag', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Poliwhirl', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Poliwrath', 120, 'Agua', 'Torrente', 'Aumenta el poder de agua', 2, 2, 'Pistola Agua', 80, 'Ataque de tipo agua', 'Electrico', 20, 'Rara'),
    ('Abra', 70, 'Psiquico', 'Sincronía', 'Comparte estados alterados', 1, 1, 'Confusion', 40, 'Ataque de tipo psiquico', 'Siniestro', 10, 'Comun'),
    ('Kadabra', 70, 'Psiquico', 'Sincronía', 'Comparte estados alterados', 1, 1, 'Confusion', 40, 'Ataque de tipo psiquico', 'Siniestro', 10, 'Comun'),
    ('Alakazam', 120, 'Psiquico', 'Sincronía', 'Comparte estados alterados', 2, 2, 'Confusion', 80, 'Ataque de tipo psiquico', 'Siniestro', 20, 'Rara'),
    ('Machop', 70, 'Lucha', 'Foco Interno', 'Evita retroceder', 1, 1, 'Golpe Karate', 40, 'Ataque de tipo lucha', 'Psiquico', 10, 'Comun'),
    ('Machoke', 70, 'Lucha', 'Foco Interno', 'Evita retroceder', 1, 1, 'Golpe Karate', 40, 'Ataque de tipo lucha', 'Psiquico', 10, 'Comun'),
    ('Machamp', 120, 'Lucha', 'Foco Interno', 'Evita retroceder', 2, 2, 'Golpe Karate', 80, 'Ataque de tipo lucha', 'Psiquico', 20, 'Rara'),
    ('Bellsprout', 70, 'Planta', 'Clorofila', 'Aumenta su poder natural', 1, 1, 'Latigo Cepa', 40, 'Ataque de tipo planta', 'Fuego', 10, 'Comun'),
    ('Weepinbell', 70, 'Planta', 'Clorofila', 'Aumenta su poder natural', 1, 1, 'Latigo Cepa', 40, 'Ataque de tipo planta', 'Fuego', 10, 'Comun'),
    ('Victreebel', 120, 'Planta', 'Clorofila', 'Aumenta su poder natural', 2, 2, 'Latigo Cepa', 80, 'Ataque de tipo planta', 'Fuego', 20, 'Rara'),
    ('Tentacool', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Tentacruel', 120, 'Agua', 'Torrente', 'Aumenta el poder de agua', 2, 2, 'Pistola Agua', 80, 'Ataque de tipo agua', 'Electrico', 20, 'Rara'),
    ('Geodude', 70, 'Roca', 'Cabeza Roca', 'Reduce daño por retroceso', 1, 1, 'Lanzarrocas', 40, 'Ataque de tipo roca', 'Agua', 10, 'Comun'),
    ('Graveler', 70, 'Roca', 'Cabeza Roca', 'Reduce daño por retroceso', 1, 1, 'Lanzarrocas', 40, 'Ataque de tipo roca', 'Agua', 10, 'Comun'),
    ('Golem', 120, 'Roca', 'Cabeza Roca', 'Reduce daño por retroceso', 2, 2, 'Lanzarrocas', 80, 'Ataque de tipo roca', 'Agua', 20, 'Rara'),
    ('Ponyta', 70, 'Fuego', 'Mar de Llamas', 'Aumenta el daño de fuego', 1, 1, 'Lanzallamas', 40, 'Ataque de tipo fuego', 'Agua', 10, 'Comun'),
    ('Rapidash', 70, 'Fuego', 'Mar de Llamas', 'Aumenta el daño de fuego', 1, 1, 'Lanzallamas', 40, 'Ataque de tipo fuego', 'Agua', 10, 'Comun'),
    ('Slowpoke', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Slowbro', 120, 'Agua', 'Torrente', 'Aumenta el poder de agua', 2, 2, 'Pistola Agua', 80, 'Ataque de tipo agua', 'Electrico', 20, 'Rara'),
    ('Magnemite', 70, 'Electrico', 'Electricidad Estatica', 'Puede paralizar al rival', 1, 1, 'Impactrueno', 40, 'Ataque de tipo electrico', 'Tierra', 10, 'Comun'),
    ('Magneton', 120, 'Electrico', 'Electricidad Estatica', 'Puede paralizar al rival', 2, 2, 'Impactrueno', 80, 'Ataque de tipo electrico', 'Tierra', 20, 'Rara'),
    ('Farfetchd', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Doduo', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Dodrio', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Seel', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Dewgong', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Grimer', 70, 'Veneno', 'Punto Toxico', 'Puede envenenar al rival', 1, 1, 'Acido', 40, 'Ataque de tipo veneno', 'Psiquico', 10, 'Comun'),
    ('Muk', 120, 'Veneno', 'Punto Toxico', 'Puede envenenar al rival', 2, 2, 'Acido', 80, 'Ataque de tipo veneno', 'Psiquico', 20, 'Rara'),
    ('Shellder', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Cloyster', 120, 'Agua', 'Torrente', 'Aumenta el poder de agua', 2, 2, 'Pistola Agua', 80, 'Ataque de tipo agua', 'Electrico', 20, 'Rara'),
    ('Gastly', 70, 'Fantasma', 'Levitacion', 'Evita ataques de tierra', 1, 1, 'Bola Sombra', 40, 'Ataque de tipo fantasma', 'Psiquico', 10, 'Comun'),
    ('Haunter', 70, 'Fantasma', 'Levitacion', 'Evita ataques de tierra', 1, 1, 'Bola Sombra', 40, 'Ataque de tipo fantasma', 'Psiquico', 10, 'Comun'),
    ('Gengar', 120, 'Fantasma', 'Levitacion', 'Evita ataques de tierra', 2, 2, 'Bola Sombra', 80, 'Ataque de tipo fantasma', 'Psiquico', 20, 'Rara'),
    ('Onix', 70, 'Roca', 'Cabeza Roca', 'Reduce daño por retroceso', 1, 1, 'Lanzarrocas', 40, 'Ataque de tipo roca', 'Agua', 10, 'Comun'),
    ('Drowzee', 70, 'Psiquico', 'Sincronía', 'Comparte estados alterados', 1, 1, 'Confusion', 40, 'Ataque de tipo psiquico', 'Siniestro', 10, 'Comun'),
    ('Hypno', 70, 'Psiquico', 'Sincronía', 'Comparte estados alterados', 1, 1, 'Confusion', 40, 'Ataque de tipo psiquico', 'Siniestro', 10, 'Comun'),
    ('Krabby', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Kingler', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Voltorb', 70, 'Electrico', 'Electricidad Estatica', 'Puede paralizar al rival', 1, 1, 'Impactrueno', 40, 'Ataque de tipo electrico', 'Tierra', 10, 'Comun'),
    ('Electrode', 70, 'Electrico', 'Electricidad Estatica', 'Puede paralizar al rival', 1, 1, 'Impactrueno', 40, 'Ataque de tipo electrico', 'Tierra', 10, 'Comun'),
    ('Exeggcute', 70, 'Planta', 'Clorofila', 'Aumenta su poder natural', 1, 1, 'Latigo Cepa', 40, 'Ataque de tipo planta', 'Fuego', 10, 'Comun'),
    ('Exeggutor', 120, 'Planta', 'Clorofila', 'Aumenta su poder natural', 2, 2, 'Latigo Cepa', 80, 'Ataque de tipo planta', 'Fuego', 20, 'Rara'),
    ('Cubone', 70, 'Tierra', 'Velo Arena', 'Mejora evasion en arena', 1, 1, 'Terremoto', 40, 'Ataque de tipo tierra', 'Agua', 10, 'Comun'),
    ('Marowak', 70, 'Tierra', 'Velo Arena', 'Mejora evasion en arena', 1, 1, 'Terremoto', 40, 'Ataque de tipo tierra', 'Agua', 10, 'Comun'),
    ('Hitmonlee', 70, 'Lucha', 'Foco Interno', 'Evita retroceder', 1, 1, 'Golpe Karate', 40, 'Ataque de tipo lucha', 'Psiquico', 10, 'Comun'),
    ('Hitmonchan', 70, 'Lucha', 'Foco Interno', 'Evita retroceder', 1, 1, 'Golpe Karate', 40, 'Ataque de tipo lucha', 'Psiquico', 10, 'Comun'),
    ('Lickitung', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Koffing', 70, 'Veneno', 'Punto Toxico', 'Puede envenenar al rival', 1, 1, 'Acido', 40, 'Ataque de tipo veneno', 'Psiquico', 10, 'Comun'),
    ('Weezing', 70, 'Veneno', 'Punto Toxico', 'Puede envenenar al rival', 1, 1, 'Acido', 40, 'Ataque de tipo veneno', 'Psiquico', 10, 'Comun'),
    ('Rhyhorn', 70, 'Tierra', 'Velo Arena', 'Mejora evasion en arena', 1, 1, 'Terremoto', 40, 'Ataque de tipo tierra', 'Agua', 10, 'Comun'),
    ('Rhydon', 120, 'Tierra', 'Velo Arena', 'Mejora evasion en arena', 2, 2, 'Terremoto', 80, 'Ataque de tipo tierra', 'Agua', 20, 'Rara'),
    ('Chansey', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Tangela', 70, 'Planta', 'Clorofila', 'Aumenta su poder natural', 1, 1, 'Latigo Cepa', 40, 'Ataque de tipo planta', 'Fuego', 10, 'Comun'),
    ('Kangaskhan', 120, 'Normal', 'Adaptable', 'Mejora ataques normales', 2, 2, 'Placaje', 80, 'Ataque de tipo normal', 'Lucha', 20, 'Rara'),
    ('Horsea', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Seadra', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Goldeen', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Seaking', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Staryu', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Starmie', 120, 'Agua', 'Torrente', 'Aumenta el poder de agua', 2, 2, 'Pistola Agua', 80, 'Ataque de tipo agua', 'Electrico', 20, 'Rara'),
    ('Mr Mime', 70, 'Psiquico', 'Sincronía', 'Comparte estados alterados', 1, 1, 'Confusion', 40, 'Ataque de tipo psiquico', 'Siniestro', 10, 'Comun'),
    ('Scyther', 120, 'Bicho', 'Enjambre', 'Aumenta ataques de bicho', 2, 2, 'Picadura', 80, 'Ataque de tipo bicho', 'Fuego', 20, 'Rara'),
    ('Jynx', 120, 'Hielo', 'Manto Niveo', 'Mejora evasion con nieve', 2, 2, 'Rayo Hielo', 80, 'Ataque de tipo hielo', 'Fuego', 20, 'Rara'),
    ('Electabuzz', 120, 'Electrico', 'Electricidad Estatica', 'Puede paralizar al rival', 2, 2, 'Impactrueno', 80, 'Ataque de tipo electrico', 'Tierra', 20, 'Rara'),
    ('Magmar', 120, 'Fuego', 'Mar de Llamas', 'Aumenta el daño de fuego', 2, 2, 'Lanzallamas', 80, 'Ataque de tipo fuego', 'Agua', 20, 'Rara'),
    ('Pinsir', 120, 'Bicho', 'Enjambre', 'Aumenta ataques de bicho', 2, 2, 'Picadura', 80, 'Ataque de tipo bicho', 'Fuego', 20, 'Rara'),
    ('Tauros', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Magikarp', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Gyarados', 120, 'Agua', 'Torrente', 'Aumenta el poder de agua', 2, 2, 'Pistola Agua', 80, 'Ataque de tipo agua', 'Electrico', 20, 'Rara'),
    ('Lapras', 120, 'Agua', 'Torrente', 'Aumenta el poder de agua', 2, 2, 'Pistola Agua', 80, 'Ataque de tipo agua', 'Electrico', 20, 'Rara'),
    ('Ditto', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Eevee', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Vaporeon', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Jolteon', 70, 'Electrico', 'Electricidad Estatica', 'Puede paralizar al rival', 1, 1, 'Impactrueno', 40, 'Ataque de tipo electrico', 'Tierra', 10, 'Comun'),
    ('Flareon', 70, 'Fuego', 'Mar de Llamas', 'Aumenta el daño de fuego', 1, 1, 'Lanzallamas', 40, 'Ataque de tipo fuego', 'Agua', 10, 'Comun'),
    ('Porygon', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Omanyte', 70, 'Roca', 'Cabeza Roca', 'Reduce daño por retroceso', 1, 1, 'Lanzarrocas', 40, 'Ataque de tipo roca', 'Agua', 10, 'Comun'),
    ('Omastar', 120, 'Roca', 'Cabeza Roca', 'Reduce daño por retroceso', 2, 2, 'Lanzarrocas', 80, 'Ataque de tipo roca', 'Agua', 20, 'Rara'),
    ('Kabuto', 70, 'Roca', 'Cabeza Roca', 'Reduce daño por retroceso', 1, 1, 'Lanzarrocas', 40, 'Ataque de tipo roca', 'Agua', 10, 'Comun'),
    ('Kabutops', 120, 'Roca', 'Cabeza Roca', 'Reduce daño por retroceso', 2, 2, 'Lanzarrocas', 80, 'Ataque de tipo roca', 'Agua', 20, 'Rara'),
    ('Aerodactyl', 120, 'Roca', 'Cabeza Roca', 'Reduce daño por retroceso', 2, 2, 'Lanzarrocas', 80, 'Ataque de tipo roca', 'Agua', 20, 'Rara'),
    ('Snorlax', 120, 'Normal', 'Adaptable', 'Mejora ataques normales', 2, 2, 'Placaje', 80, 'Ataque de tipo normal', 'Lucha', 20, 'Rara'),
    ('Articuno', 150, 'Hielo', 'Manto Niveo', 'Mejora evasion con nieve', 3, 3, 'Rayo Hielo', 120, 'Ataque de tipo hielo', 'Fuego', 20, 'Legendaria'),
    ('Zapdos', 150, 'Electrico', 'Electricidad Estatica', 'Puede paralizar al rival', 3, 3, 'Impactrueno', 120, 'Ataque de tipo electrico', 'Tierra', 20, 'Legendaria'),
    ('Moltres', 150, 'Fuego', 'Mar de Llamas', 'Aumenta el daño de fuego', 3, 3, 'Lanzallamas', 120, 'Ataque de tipo fuego', 'Agua', 20, 'Legendaria'),
    ('Dratini', 70, 'Dragon', 'Multiescamas', 'Reduce daño recibido', 1, 1, 'Pulso Dragon', 40, 'Ataque de tipo dragon', 'Hielo', 10, 'Comun'),
    ('Dragonair', 70, 'Dragon', 'Multiescamas', 'Reduce daño recibido', 1, 1, 'Pulso Dragon', 40, 'Ataque de tipo dragon', 'Hielo', 10, 'Comun'),
    ('Dragonite', 120, 'Dragon', 'Multiescamas', 'Reduce daño recibido', 2, 2, 'Pulso Dragon', 80, 'Ataque de tipo dragon', 'Hielo', 20, 'Rara'),
    ('Mewtwo', 150, 'Psiquico', 'Sincronía', 'Comparte estados alterados', 3, 3, 'Confusion', 120, 'Ataque de tipo psiquico', 'Siniestro', 20, 'Legendaria'),
    ('Mew', 150, 'Psiquico', 'Sincronía', 'Comparte estados alterados', 3, 3, 'Confusion', 120, 'Ataque de tipo psiquico', 'Siniestro', 20, 'Legendaria'),
    ('Chikorita', 70, 'Planta', 'Clorofila', 'Aumenta su poder natural', 1, 1, 'Latigo Cepa', 40, 'Ataque de tipo planta', 'Fuego', 10, 'Comun'),
    ('Bayleef', 70, 'Planta', 'Clorofila', 'Aumenta su poder natural', 1, 1, 'Latigo Cepa', 40, 'Ataque de tipo planta', 'Fuego', 10, 'Comun'),
    ('Meganium', 120, 'Planta', 'Clorofila', 'Aumenta su poder natural', 2, 2, 'Latigo Cepa', 80, 'Ataque de tipo planta', 'Fuego', 20, 'Rara'),
    ('Cyndaquil', 70, 'Fuego', 'Mar de Llamas', 'Aumenta el daño de fuego', 1, 1, 'Lanzallamas', 40, 'Ataque de tipo fuego', 'Agua', 10, 'Comun'),
    ('Quilava', 70, 'Fuego', 'Mar de Llamas', 'Aumenta el daño de fuego', 1, 1, 'Lanzallamas', 40, 'Ataque de tipo fuego', 'Agua', 10, 'Comun'),
    ('Typhlosion', 120, 'Fuego', 'Mar de Llamas', 'Aumenta el daño de fuego', 2, 2, 'Lanzallamas', 80, 'Ataque de tipo fuego', 'Agua', 20, 'Rara'),
    ('Totodile', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Croconaw', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Feraligatr', 120, 'Agua', 'Torrente', 'Aumenta el poder de agua', 2, 2, 'Pistola Agua', 80, 'Ataque de tipo agua', 'Electrico', 20, 'Rara'),
    ('Sentret', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Furret', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Hoothoot', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Noctowl', 120, 'Normal', 'Adaptable', 'Mejora ataques normales', 2, 2, 'Placaje', 80, 'Ataque de tipo normal', 'Lucha', 20, 'Rara'),
    ('Ledyba', 70, 'Bicho', 'Enjambre', 'Aumenta ataques de bicho', 1, 1, 'Picadura', 40, 'Ataque de tipo bicho', 'Fuego', 10, 'Comun'),
    ('Ledian', 120, 'Bicho', 'Enjambre', 'Aumenta ataques de bicho', 2, 2, 'Picadura', 80, 'Ataque de tipo bicho', 'Fuego', 20, 'Rara'),
    ('Spinarak', 70, 'Bicho', 'Enjambre', 'Aumenta ataques de bicho', 1, 1, 'Picadura', 40, 'Ataque de tipo bicho', 'Fuego', 10, 'Comun'),
    ('Ariados', 120, 'Bicho', 'Enjambre', 'Aumenta ataques de bicho', 2, 2, 'Picadura', 80, 'Ataque de tipo bicho', 'Fuego', 20, 'Rara'),
    ('Crobat', 120, 'Veneno', 'Punto Toxico', 'Puede envenenar al rival', 2, 2, 'Acido', 80, 'Ataque de tipo veneno', 'Psiquico', 20, 'Rara'),
    ('Chinchou', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Lanturn', 120, 'Agua', 'Torrente', 'Aumenta el poder de agua', 2, 2, 'Pistola Agua', 80, 'Ataque de tipo agua', 'Electrico', 20, 'Rara'),
    ('Pichu', 70, 'Electrico', 'Electricidad Estatica', 'Puede paralizar al rival', 1, 1, 'Impactrueno', 40, 'Ataque de tipo electrico', 'Tierra', 10, 'Comun'),
    ('Cleffa', 70, 'Hada', 'Gran Encanto', 'Puede reducir ataque rival', 1, 1, 'Brillo Magico', 40, 'Ataque de tipo hada', 'Veneno', 10, 'Comun'),
    ('Igglybuff', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Togepi', 70, 'Hada', 'Gran Encanto', 'Puede reducir ataque rival', 1, 1, 'Brillo Magico', 40, 'Ataque de tipo hada', 'Veneno', 10, 'Comun'),
    ('Togetic', 120, 'Hada', 'Gran Encanto', 'Puede reducir ataque rival', 2, 2, 'Brillo Magico', 80, 'Ataque de tipo hada', 'Veneno', 20, 'Rara'),
    ('Natu', 70, 'Psiquico', 'Sincronía', 'Comparte estados alterados', 1, 1, 'Confusion', 40, 'Ataque de tipo psiquico', 'Siniestro', 10, 'Comun'),
    ('Xatu', 120, 'Psiquico', 'Sincronía', 'Comparte estados alterados', 2, 2, 'Confusion', 80, 'Ataque de tipo psiquico', 'Siniestro', 20, 'Rara'),
    ('Mareep', 70, 'Electrico', 'Electricidad Estatica', 'Puede paralizar al rival', 1, 1, 'Impactrueno', 40, 'Ataque de tipo electrico', 'Tierra', 10, 'Comun'),
    ('Flaaffy', 70, 'Electrico', 'Electricidad Estatica', 'Puede paralizar al rival', 1, 1, 'Impactrueno', 40, 'Ataque de tipo electrico', 'Tierra', 10, 'Comun'),
    ('Ampharos', 120, 'Electrico', 'Electricidad Estatica', 'Puede paralizar al rival', 2, 2, 'Impactrueno', 80, 'Ataque de tipo electrico', 'Tierra', 20, 'Rara'),
    ('Bellossom', 120, 'Planta', 'Clorofila', 'Aumenta su poder natural', 2, 2, 'Latigo Cepa', 80, 'Ataque de tipo planta', 'Fuego', 20, 'Rara'),
    ('Marill', 70, 'Agua', 'Torrente', 'Aumenta el poder de agua', 1, 1, 'Pistola Agua', 40, 'Ataque de tipo agua', 'Electrico', 10, 'Comun'),
    ('Azumarill', 120, 'Agua', 'Torrente', 'Aumenta el poder de agua', 2, 2, 'Pistola Agua', 80, 'Ataque de tipo agua', 'Electrico', 20, 'Rara'),
    ('Sudowoodo', 120, 'Roca', 'Cabeza Roca', 'Reduce daño por retroceso', 2, 2, 'Lanzarrocas', 80, 'Ataque de tipo roca', 'Agua', 20, 'Rara'),
    ('Politoed', 120, 'Agua', 'Torrente', 'Aumenta el poder de agua', 2, 2, 'Pistola Agua', 80, 'Ataque de tipo agua', 'Electrico', 20, 'Rara'),
    ('Hoppip', 70, 'Planta', 'Clorofila', 'Aumenta su poder natural', 1, 1, 'Latigo Cepa', 40, 'Ataque de tipo planta', 'Fuego', 10, 'Comun'),
    ('Skiploom', 70, 'Planta', 'Clorofila', 'Aumenta su poder natural', 1, 1, 'Latigo Cepa', 40, 'Ataque de tipo planta', 'Fuego', 10, 'Comun'),
    ('Jumpluff', 120, 'Planta', 'Clorofila', 'Aumenta su poder natural', 2, 2, 'Latigo Cepa', 80, 'Ataque de tipo planta', 'Fuego', 20, 'Rara'),
    ('Aipom', 70, 'Normal', 'Adaptable', 'Mejora ataques normales', 1, 1, 'Placaje', 40, 'Ataque de tipo normal', 'Lucha', 10, 'Comun'),
    ('Sunkern', 70, 'Planta', 'Clorofila', 'Aumenta su poder natural', 1, 1, 'Latigo Cepa', 40, 'Ataque de tipo planta', 'Fuego', 10, 'Comun');