spring:
  application:
    name: PokeTrade
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

usuario-service:
  url: ${USUARIO_SERVICE_URL}
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
usuario-service:
  url: ${USUARIO_SERVICE_URL}
server:
  port: ${PORT}
  address: 0.0.0.0