spring:
  application:
    name: apiGateway
---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: usuario-services
              uri: http://localhost:8081
              predicates:
                - Path=/usuarios/**
              filters:
                - StripPrefix=1
            - id: poketrade-services
              uri: http://localhost:8080
              predicates:
                - Path=/poketrade/**
              filters:
                - StripPrefix=1
server:
  port: 8090
---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: usuario-services
              uri: ${USUARIO_SERVICE_URL}
              predicates:
                - Path=/usuarios/**
              filters:
                - StripPrefix=1
            - id: poketrade-services
              uri: ${POKETRADE_SERVICE_URL}
              predicates:
                - Path=/poketrade/**
              filters:
                - StripPrefix=1
server:
  port: ${PORT:8080}